[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
build_flags =
    -Werror=unused-result
    -std=gnu++17
    -DUSE_CUSTOM_LOGGER
    -DCONFIG_ETH_ENABLED=1
    -DCONFIG_WIFI_ENABLED=0
    -DCONFIG_MDNS_DISABLE=1
    -DDEVICE_HOSTNAME=\"esp32-ethernet-device\"
    -DETH_PHY_MDC_PIN=23
    -DETH_PHY_MDIO_PIN=18
    -DETH_PHY_ADDR=0
    -DETH_PHY_POWER_PIN=-1
    -DSTATUS_LED_PIN=2
    -DOTA_PASSWORD=\"update-password\"
build_unflags =
    -std=gnu++11
lib_deps =
    symlink://../..
    https://github.com/packerlschupfer/ESP32-MutexGuard.git
    https://github.com/packerlschupfer/ESP32-Logger.git
    https://github.com/packerlschupfer/ESP32-SemaphoreGuard.git
    https://github.com/packerlschupfer/ESP32-EthernetManager.git
    https://github.com/packerlschupfer/ESP32-TaskManager.git

[env:core2_espressif32]
extends = env:esp32dev
platform = espressif32
